
postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: Matterhorn1. 
      port: 5432
      dbname: electro
      schema: public
      threads: 1
      keepalives_idle: 0 
      connect_timeout: 10 
















