
postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airbyte
      password: Matterhorn1. 
      port: 5432
      dbname: mydb
      schema: public
      threads: 1
      keepalives_idle: 0 
      connect_timeout: 10 
















